### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by qoeogns09** [BioGenies/AMPBenchmark#1]
Hello, I'm interested in your study and AMP activity prediction using AI.

I want to use AMPBenchmark in my study. But I have some question about AMPBenchmark training sets.

There exists 5 repeats training sets. When I upload benchmark set result, should I upload 5 times for each repeated training set or average of 5 times probabilities?

Thank you for reading.

**Comment by ksidorczuk** [comment]
Hi, thank you for using AMPBenchmark.

You should upload one file containing all results from all replications (without averaging). The replication number will be extracted automatically by AMPBenchmark from the sequence name column. 

We provide an exemplary file showing how the data should be formatted. It can be downloaded from Dropbox: https://www.dropbox.com/s/sg93msr3ufvpn4o/sample_data.csv?dl=0
It is just one file combining all the results and you can notice there that the ID column contains names of peptides from all five replications (e.g. rep1 at the end of the name). It is important that you use the original names of our sequences in this column, as it is necessary for proper data processing.

**Comment by qoeogns09** [comment]
Thank you for reply. But I have remaining question.

After training my model, there exists 55 models(11 negative sampling methods * 5 replication training sets)
But, provided sample data format contains only 11 models benchmarks set results.

When I implement test, should I pairing train replication and test replication number?
example)
- train replication 1 for testing test replication 1
- train replication 2 for testing test replication 2
- train replication 3 for testing test replication 3
- train replication 4 for testing test replication 4
- train replication 5 for testing test replication 5

**Comment by ksidorczuk** [comment]
Yes, testing should be done within replications. You should pair them as in your example. 

Essentially, one replication means that we run the whole procedure of sampling train and test sets once. Train and test sets are created together to prevent information leakage. Therefore, each training replication has a corresponding test replication meant to be used with it.

**Comment by qoeogns09** [comment]
Okay, I understanding your methods and intention.

Thank you for nice works and sharing your study.

**Comment by qoeogns09** [comment]
Provided exemplary file and AMPBenchmark web server have some problem.

When I download and check this file(Dropbox: https://www.dropbox.com/s/sg93msr3ufvpn4o/sample_data.csv?dl=0), columns name is strange.

I think "benchmark_sampling" should be change to "training_sampling"

Also, "README" example format "training_sampling" but it does not work on AMPBenchmark web server.
When columns name is benchmark_sampling is works.

+ I checked my model performance on AMPBenchmark, but 
![image](https://user-images.githubusercontent.com/76238341/211760582-fe7bdcfb-f0dd-4ff1-94b0-3a8154733887.png)

If same training sampling methods shows same performance regardless of benchmark sampling methods
So, I checked my result data. but it does not shows same performance. Could you please check about your server?

**Comment by michbur** [comment]
> If same training sampling methods shows same performance regardless of benchmark sampling methods So, I checked my result data. but it does not shows same performance. Could you please check about your server?

You were right. Unfortunately, our web server was not processing data correctly. We have updated the server and it should work properly now. 

The dataset is updated and the link is still the same: https://www.dropbox.com/s/uw312pycmhevggm/sample_data.csv?dl=0.

Thank you a lot for your contribution

**Comment by qoeogns09** [comment]
Thank you for fast response. This study is very helpful for me.

I have a one more suggestion. When I use AMPBenchmark server, page and download table shows only 50 rows of result.
Could you please extend rows to 55? It is possible to check all result, but uncomfortable to check 55 results of new model.

**Comment by michbur** [comment]
@ksidorczuk added it, thank you so much for this suggestion @qoeogns09.

**Comment by qoeogns09** [comment]
In AMPBenchmark server, Impact of the sampling method part is little awkward.

AMPScannerV2 shows best performance with same sampling methods in figure and paper, but it shows best performance with different sampling methods in server results table.

I think it may changed with "different methods" and "same method" column names in server results table.

**Comment by ksidorczuk** [comment]
You're right. Indeed, the column names were swapped. 

It has been corrected and should be visible on the web server shortly.

**Comment by michbur** [comment]
@qoeogns09 we have hosted the improved version. Let us know if it works properly. Thank you very much for your corrections.

**Comment by qoeogns09** [comment]
Yes, I checked it. It works well. Thank you for fast response.
