### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by cfz1998** [BioGenies/AMPBenchmark#2]
Hello! @michbur  @ksidorczuk 

The links are not accessible.
https://www.dropbox.com/sh/e489gp126ownv3n/AAC_KAI5yDSX2aJhJ0G9ZMnha?dl=0

**Comment by ksidorczuk** [comment]
Hi @cfz1998 
I'm sorry for a delayed reply. I updated the links, all should be working now.

**Comment by cfz1998** [comment]
Thank you for your help! :tada:
